version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=myapp

  app:
    build: .
    volumes:
      - .:/app
    environment:
      - AWS_REGION=ap-northeast-1
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
      - POSTGRES_DB=myapp
